url: "https://montagesubs.github.io" 
baseurl: ""

collections:
  works:
    output: true
  pages:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - scripts/
  - scripts/**/*
